name: Build and Release
on:
  push:
    tags:
      - "*"
jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create Android Signing Key Store File
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY_STORE }}" > upload-keystore.jks.b64
          base64 -d -i upload-keystore.jks.b64 > android/app/upload-keystore.jks
      - name: Create Android Signing Key Properties File
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY_PROPERTIES }}" > key.properties.b64
          base64 -d -i key.properties.b64 > android/key.properties
      - name: Create Firebase Android App Credentials
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > google-services.json.b64
          base64 -d -i google-services.json.b64 > android/app/google-services.json
      - name: Create Firebase Options Dart
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > firebase_options.dart.b64
          base64 -d -i firebase_options.dart.b64 > lib/firebase_options.dart
      - name: Create Firebase App Distribution Credentials
        run: |
          echo "${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}" > food-stock-app-ce.json.b64
          base64 -d -i food-stock-app-ce.json.b64 > food-stock-app-ce.json
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.1"
          channel: "stable"
      - name: Build APK
        run: flutter build apk lib/main.dart --build-name=$GITHUB_REF_NAME --build-number=$GITHUB_RUN_NUMBER --release
      - name: Deploy Android App to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: food-stock-app-ce.json
          groups: foodstock
          file: build/app/outputs/apk/release/app-release.apk
          releaseNotesFile: release_notes.txt
      - name: Cleanup Environment
        if: ${{ always() }}
        run: |
          # Remove credentials
          rm -rf android/app/google-services.json
          rm -rf google-services.json.b64
          rm -rf upload-keystore.jks.b64
          rm -rf key.properties.b64
          rm -rf android/app/upload-keystore.jks
          rm -rf android/key.properties
          rm -rf firebase_options.dart.b64
          rm -rf lib/firebase_options.dart
          rm -rf food-stock-app-ce.json
          rm -rf food-stock-app-ce.json.b64
